export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = "GET_PROFILEs";
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_ZONES = 'GET_ZONES';
